#!/usr/bin/env python
# coding: utf-8
from sklearn.cluster import KMeans
import numpy as np
import matplotlib.pyplot as plt


X = np.array([[1, 2], [1, 4], [1, 0],
              [4, 2], [4, 4], [4, 0]])


kmeans = KMeans(n_clusters=2, random_state=0).fit(X)


print(kmeans.labels_)
print(kmeans.cluster_centers_)


#In the above result (X[0], X[1], X[2]) label 0, if the last three results (X[3], X[4], X[5])
#It belonged to label 1. Cluster centers were found as (1, 2) for cluster 0 and (4, 2) for cluster 1.


#results
plt.scatter(X[:, 0], X[:, 1], c=kmeans.labels_, cmap='viridis')


#cluster centers
centers = kmeans.cluster_centers_
plt.scatter(centers[:, 0], centers[:, 1], c='black', s=200, alpha=0.5)




